# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

a_star_norm <- function(mean_p, sd_p, mean_n, sd_n, do_log) {
    .Call(`_negmix_a_star_norm`, mean_p, sd_p, mean_n, sd_n, do_log)
}

a_star_gam <- function(alpha_p, beta_p, alpha_n, beta_n, do_log) {
    .Call(`_negmix_a_star_gam`, alpha_p, beta_p, alpha_n, beta_n, do_log)
}

toto <- function(a, b) {
    .Call(`_negmix_toto`, a, b)
}

cpp_map_pairs <- function(delta, par, family) {
    .Call(`_negmix_cpp_map_pairs`, delta, par, family)
}

build_pairing <- function(delta, par, family, tol_simplex) {
    .Call(`_negmix_build_pairing`, delta, par, family, tol_simplex)
}

dnormix <- function(x, w, mean, sd) {
    .Call(`_negmix_dnormix`, x, w, mean, sd)
}

dgammix <- function(x, w, alpha, beta) {
    .Call(`_negmix_dgammix`, x, w, alpha, beta)
}

pnormix <- function(x, w, mean, sd) {
    .Call(`_negmix_pnormix`, x, w, mean, sd)
}

pgammix <- function(x, w, alpha, inv_beta) {
    .Call(`_negmix_pgammix`, x, w, alpha, inv_beta)
}

cpp_qnegmix <- function(x, par, family, precision, n_bins) {
    .Call(`_negmix_cpp_qnegmix`, x, par, family, precision, n_bins)
}

render_model <- function(k_p, k_n, family, par, by_2, control) {
    .Call(`_negmix_render_model`, k_p, k_n, family, par, by_2, control)
}

cpp_rnegmix <- function(n, par, family, method, control) {
    .Call(`_negmix_cpp_rnegmix`, n, par, family, method, control)
}

